apiVersion: apps/v1
kind: Deployment
metadata:
  name: wgeasy
  namespace: kubeseed
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: wgeasy
          ports:
            - containerPort: 51820
              protocol: UDP
          securityContext:
            privileged: true
