---
- name: wait for files to be present
  wait_for:
    path:
      "{{ lookup('env', 'APP_SETTINGS') }}/{{application}}/config/rtorrent/.rtorrent.rc"

- name: Create directory
  file:
    path: "/home/{{ lookup('env','USER') }}/local/{{application}}"
    state: directory

- name: Set download location
  lineinfile:
    path:
      "{{ lookup('env', 'APP_SETTINGS') }}/{{application}}/config/rtorrent/.rtorrent.rc"
    regexp: '#*directory.default.set\s*=.*'
    line: "directory.default.set = /home/{{ lookup('env','USER') }}/local/{{application}}"
    state: present

- name: Set download location
  lineinfile:
    path:
      "{{ lookup('env', 'APP_SETTINGS') }}/{{application}}/config/rutorrent/conf/config.php"
    regexp: '\$topDirectory\s*=.*'
    line: "$topDirectory = '/home/{{ lookup('env','USER') }}';"
    state: present

- name: Change port
  lineinfile:
    path:
      "{{ lookup('env', 'APP_SETTINGS') }}/{{application}}/config/rtorrent/.rtorrent.rc"
    regexp: '#*network.port_range.set\s*=.*'
    line: "network.port_range.set = {{ specific_container_info.ports[0] }}-{{ specific_container_info.ports[0] }}"
    state: present

- name: Clone Ratio Color plugin
  git:
    repo: https://github.com/Micdu70/rutorrent-ratiocolor.git
    dest: "{{ lookup('env', 'APP_SETTINGS') }}/{{application}}/config/custom_plugins/ratiocolor"
    clone: yes
