- name: create config directory exists
  file:
    path: "{{ lookup('env', 'APP_SETTINGS') }}/{{application}}/config"
    state: directory

- name: Create file
  file:
    path: "{{ lookup('env', 'APP_SETTINGS') }}/{{application}}/config/conf.yml"
    state: touch
