---
- name: Launch post n8nio task
  kubernetes.core.k8s:
    api_version: v1
    kubeconfig: "{{ settings.storage }}/k3s/k3s.yaml"
    kind: Pod
    namespace: kubeseed
    name: n8nio-job
    definition:
      metadata:
        labels:
          ksapp: "{{ application }}"
          app: "{{ application }}"
      spec:
        containers:
        - name: chown-container
          image: n8nio/base:16
          command: ["chown", "-Rv", "node:node", "/home/node/.n8n"]
          volumeMounts:
          - name: n8n-settings
            mountPath: /home/node/.n8n
        volumes:
        - name: n8n-settings
          hostPath:
            path: "{{ lookup('env', 'APP_SETTINGS') }}/{{application}}/config"
        restartPolicy: "Never"
        