---
- name: Set facts
  set_fact:
    dbimage: "postgres"
    db_app_port: 5432
    db_persistent_path: "/var/lib/postgresql/data"
    db_application_env:
      - name: "POSTGRES_DB"
        value: "{{ application }}"
      - name: "POSTGRES_USER"
        value: "{{ application }}"
      - name: "POSTGRES_PASSWORD"
        value: "{{ application }}"

- name: Launch databasess
  include_tasks: "{{ settings.source }}/containers/tasks/bdd.yml"

