---
- name: Check JSON exists
  stat:
    path: "{{ settings.storage }}/docker//{{ application }}/appsettings.json"
  register: jsonfile

- name: Make sure directory is present
  file:
    path: "{{ settings.storage }}/docker/{{ application }}"
    state: directory

- name: 'Download {{ application }} appsettings.json config file'
  get_url:
    url: 
      https://raw.githubusercontent.com/tidusjar/Ombi/master/src/Ombi/appsettings.json
    dest: "{{ settings.storage }}/docker/{{ application }}/appsettings.json"
    owner: '{{ user.userid }}'
    group: '{{ user.groupid }}'
    force: false
  ignore_errors: true
  when: not jsonfile.stat.exists
