# Permet de relancer un déploiement (replica 1)
- name: "Restart {{ application }}"
  shell: "/bin/bash -c 'kubectl scale deployment {{ application }} --replicas 1 -n kubeseed'"
  environment:
    KUBECONFIG: "{{ settings.storage }}/k3s/k3s.yaml"
