cf_enabled: "{{ true if not(
    (cloudflare.login is undefined)
    or
    (cloudflare.login is none)
    or
    (cloudflare.login | trim | length == 0)
    or
    (cloudflare.api is undefined)
    or
    (cloudflare.api is none)
    or
    (cloudflare.api | trim | length == 0)
    )
    else false }}"

nsup_enabled: "{{ true if not(
    (dns.keyname is undefined)
    or
    (dns.keyname is none)
    or
    (dns.keyname | trim | length == 0)
    or
    (dns.keysecret is undefined)
    or
    (dns.keysecret is none)
    or
    (dns.keysecret | trim | length == 0)
    )
    else false }}"