---
- name: prepare host volume
  set_fact:
    temp_dict:
      - name: "{{ application }}-{{ detail_volume.container_path| replace('/','')  }}"
        hostPath:
          path: "{{ detail_volume.local_path }}"
          type: DirectoryOrCreate

- name: append host volume
  set_fact:
    host_volumes: "{{ host_volumes + temp_dict }}"

- name: prepare container volume
  set_fact:
    temp_dict:
      - mountPath: "{{ detail_volume.container_path }}"
        name: "{{ application}}-{{ detail_volume.container_path| replace('/','')  }}"

- name: append container volume
  set_fact:
    container_volumes: "{{ container_volumes + temp_dict }}"
