---
### CLOUDFLARE IPv4 ###
- name: Remove DNS Record A in CloudFlare
  cloudflare_dns:
    account_api_token: "{{ cloudflare.api }}"
    account_email: "{{ cloudflare.login }}"
    zone: "{{ user.domain }}"
    state: absent
    proxied: yes
    type: A
    record: "{{ subdomain }}"
  when: cloudflare.usage == "O"

### PDNS/NSUPDATE IPv4 ###
- name: Remove DNS Record A in NSUPDATE 
  community.general.nsupdate:
    key_algorithm: "{{ dns.algo }}"
    key_name: "{{ dns.keyname }}"
    key_secret: "{{ dns.keysecret }}"
    server: "{{ dns.server }}"
    zone: "{{ user.domain }}"
    record: "{{ subdomain }}"
    value: "{{ network.ipv4 }}"
    type: "A"
    state: absent
  when: dns.usage == "O"

### CLOUDFLARE IPv6 ###
- name: Remove DNS Record AAAA in CloudFlare
  cloudflare_dns:
    account_api_token: "{{ cloudflare.api }}"
    account_email: "{{ cloudflare.login }}"
    zone: "{{ user.domain }}"
    state: absent
    proxied: yes
    type: AAAA
    record: "{{ subdomain }}"
  when: cloudflare.usage == "O" and network.ipv6 != 'YAPAS'

### PDNS/NSUPDATE IPv6 ###
- name: Remove DNS Record AAAA in NSUPDATE 
  community.general.nsupdate:
    key_algorithm: "{{ dns.algo }}"
    key_name: "{{ dns.keyname }}"
    key_secret: "{{ dns.keysecret }}"
    server: "{{ dns.server }}"
    zone: "{{ user.domain }}"
    record: "{{ subdomain }}"
    value: "{{ network.ipv6 }}"
    type: "AAAA"
    state: absent
  when: dns.usage == "O" and network.ipv6 != 'YAPAS'