---
- name: Set DNS Record
  cloudflare_dns:
    account_api_token: "{{ cloudflare.api }}"
    account_email: "{{ cloudflare.login }}"
    zone: "{{ user.domain }}"
    state: absent
    proxied: true
    type: A
    record: "{{ subdomain }}"
