---
- name: Remove DNS Record
  cloudflare_dns:
    account_api_token: "{{ cloudflare.api }}"
    account_email: "{{ cloudflare.login }}"
    zone: "{{ user.domain }}"
    state: absent
    proxied: yes
    type: A
    record: "{{ subdomain }}"


- name: Remove record for ipv6
  cloudflare_dns:
    account_api_token: "{{ cloudflare.api }}"
    account_email: "{{ cloudflare.login }}"
    zone: "{{ user.domain }}"
    state: absent
    proxied: yes
    type: AAAA
    record: "{{ subdomain }}"
  when: (network.ipv6 is defined) and (network.ipv6|length > 0)