---
### CLOUDFLARE ###
- name: Remove DNS Record in CloudFlare
  cloudflare_dns:
    account_api_token: "{{ cloudflare.api }}"
    account_email: "{{ cloudflare.login }}"
    zone: "{{ user.domain }}"
    state: absent
    proxied: yes
    type: A
    record: "{{ subdomain }}"
  when: cloudflare.usage == "O"

### PDNS/NSUPDATE ###
- name: Remove DNS Record in NSUPDATE
  community.general.nsupdate:
    key_algorithm: "{{ dns.algo }}"
    key_name: "{{ dns.keyname }}"
    key_secret: "{{ dns.keysecret }}"
    server: "{{ dns.server }}"
    zone: "{{ user.domain }}"
    record: "{{ subdomain }}"
    value: "{{ network.ipv4 }}"
    type: "A"
    state: absent
  when: dns.usage == "O"
