- name: set middleware
  set_fact:
    k3s_middlewares: default-redirect-https@kubernetescrd

- name: modify middleware if basic auth
  set_fact:
    k3s_middlewares: kubeseed-my-basic-auth@kubernetescrd, default-redirect-https@kubernetescrd
  when: applis[application].auth == "basique"

- name: modify middleware if oauth
  set_fact:
    k3s_middlewares: kubeseed-oauth@kubernetescrd, default-redirect-https@kubernetescrd
  when: applis[application].auth == "oauth"