---
- hosts: localhost
  gather_facts: false
  become: True
  tasks:
    - name: Check if drive1.anchor exists
      stat:
        path: "{{ settings.storage }}/local/drive1.anchor"
      register: anchor_service

    - name: Create file anchor
      shell: |
        touch {{ settings.storage }}/local/drive1.anchor
      when: not anchor_service.stat.exists

    - name: Create directory
      file:
        path: "{{ lookup('env','APP_SETTINGS') }}/autoscan"
        state: directory

    - name: Create conf file
      template:
        src: "{{ settings.source }}/includes/playbooks/templates/autoscan.config.yaml.j2"
        dest: "{{ lookup('env','APP_SETTINGS') }}/autoscan/config.yml"


    - name: "Launch Autoscan"
      kubernetes.core.k8s:
        api_version: apps/v1
        kubeconfig: "{{ settings.storage }}/k3s/k3s.yaml"
        kind: Deployment
        namespace: kubeseed
        name: "autoscan"
        definition:
          metadata:
            labels:
              ksapp: "autoscan"
              app: "autoscan"
          spec:
            replicas: 1
            selector:
              matchLabels:
                ksapp: "autoscan"
                app: "autoscan"
            template:
              metadata:
                labels:
                  ksapp: "autoscan"
                  app: "autoscan"
              spec:
                containers:
                  - name: "autoscan"
                    image: 'cloudb0x/autoscan'
                    imagePullPolicy: "Always"
                    env:
                      - name: PUID
                        value: "{{ user.userid }}"
                      - name: PGID
                        value: "{{ user.groupid }}"
                      - name: AUTOSCAN_VERBOSITY
                        value: "2"

                    volumeMounts:
                      - mountPath: "/config"
                        name: "autoscan-config"
                      - mountPath: "{{ lookup('env','HOME') }}"
                        name: "autoscan-home"
                      - mountPath: "{{ settings.storage }}"
                        name: "autoscan-settings-storage"
                volumes:
                  - name: "autoscan-home"
                    hostPath:
                      path: "{{ lookup('env','HOME') }}"
                      type: Directory
                  - name: "autoscan-config"
                    hostPath:
                      path: "{{ lookup('env','APP_SETTINGS') }}/autoscan"
                      type: Directory
                  - name: "autoscan-settings-storage"
                    hostPath:
                      path: "{{ settings.storage }}"
                      type: Directory

    - name: "Launch autoscan - Service"
      kubernetes.core.k8s:
        kubeconfig: "{{ settings.storage }}/k3s/k3s.yaml"
        state: present
        kind: Service
        namespace: kubeseed
        name: "autoscan"
        definition:
          metadata:
            labels:
              ksapp: "autoscan"
              app: "autoscan"
          spec:
            selector:
              ksapp: "autoscan"
              app: "autoscan"
            ports:
              - protocol: TCP
                port: 3030
