---
- hosts: localhost
  gather_facts: false
  become: true
  tasks:
  - name: "Change directory {{ DIRECTORY }} rights"
    file:
      path: "{{ DIRECTORY }}"
      state: directory
      mode: 0777
