---
- hosts: localhost
  gather_facts: false
  vars_files:
    - "{{ settings.source }}/includes/playbooks/tasks/nsup_or_cf.yml"
  
  tasks:
  - name: Set DNS Record
    include_tasks:
      "{{ settings.source }}/includes/playbooks/tasks/cloudflare_domain.yml"
    vars:
      subdomain: "{{  applis[application].subdomain}}"

  - name: Display DNS Record
    debug:
      msg:
        "DNS Record for '{{ subdomain }}.{{ user.domain }}' set to '{{ network.ipv4 }}'."
