---
- hosts: localhost
  gather_facts: false

  tasks:
  - name: Remove DNS Record
    include_tasks:
      "{{ settings.source }}/includes/playbooks/tasks/remove_cf_record.yml"
    vars:
      subdomain: "{{  applis[application].subdomain}}"


