#########################################################################
# Title:         Cloudbox: Cloudflare Role                              #
# Author(s):     l3uddz, desimaniac                                     #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:

  - name: Set DNS Record
    include_tasks:
      "{{ settings.source }}/includes/playbooks/tasks/cloudflare_domain.yml"
    vars:
      subdomain: "{{  applis[application].subdomain}}"

  - name: Display DNS Record
    debug:
      msg:
        "DNS Record for '{{ subdomain }}.{{ user.domain }}' set to '{{ network.ipv4 }}'."
