---
- hosts: localhost
  gather_facts: false
  tasks:

  - name: "Install env in profile"
    ansible.builtin.blockinfile:
      path: "{{ lookup('env','HOME') }}/.bashrc"
      block: |
        if [ -f "{{ settings.source }}/profile.sh" ]; then
          source "{{ settings.source }}/profile.sh"
        fi

  - name: "Install alias"
    ansible.builtin.lineinfile:
      path: "{{ lookup('env','HOME') }}/.bashrc"
      line: "alias seedbox='cd {{ settings.source }} && ./seedbox.sh'"
