---
- hosts: localhost
  gather_facts: false
  tasks:

  - name: "Install env in profile"
    ansible.builtin.blockinfile:
      path: "{{ lookup('env','HOME') }}/.bashrc"
      block: |
        if [ -f "{{ settings.source }}/profile.sh" ]; then
          source "{{ settings.source }}/profile.sh"
        fi
