---
- hosts: localhost
  gather_facts: false
    
  tasks:
  - name: Create secret file
    template:
      src: "{{ settings.source }}/includes/playbooks/templates/k3s_secret.j2"
      dest: /tmp/k3ssec


  - name: apply secret
    kubernetes.core.k8s:
      kubeconfig: "{{ settings.storage }}/k3s/k3s.yaml"
      state: present
      src: /tmp/k3ssec

  - name: Delete temp file
    file:
      path: /tmp/k3ssec
      state: absent

