---
- hosts: localhost
  gather_facts: false

  tasks:
  - name: Create admin user
    kubernetes.core.k8s:
      kubeconfig: "{{ settings.storage }}/k3s/k3s.yaml"
      state: present
      kind: Secret
      namespace: default
      name: basic-auth-secret
      definition:
        data:
          users: |2
            {{ user.k3s_secret }}

