---
- hosts: localhost
  gather_facts: false

  tasks:
  - name: Create Secret
    kubernetes.core.k8s:
      kubeconfig: "{{ settings.storage }}/k3s/k3s.yaml"
      state: present
      kind: Secret
      namespace: "{{ my_namespace}}"
      name: basic-auth-secret
      definition:
        data:
          users: |2
            {{ user.k3s_secret }}
    loop:
      - kube-system
      - kubeseed
    loop_control:
      loop_var: my_namespace

  - name: Wait for service to be up
    pause:
      seconds: 10

  - name: Create middleware
    kubernetes.core.k8s:
      kubeconfig: "{{ settings.storage }}/k3s/k3s.yaml"
      state: present
      kind: Middleware
      namespace: "{{ my_namespace}}"
      definition:
        apiVersion: traefik.containo.us/v1alpha1
        metadata:
          name: my-basic-auth
        spec:
          basicAuth:
            secret: basic-auth-secret
    loop:
      - kube-system
      - kubeseed
    loop_control:
      loop_var: my_namespace
