---
- hosts: localhost
  gather_facts: false

  tasks:
  - name: "Create Namespace {{ ns }}"
    kubernetes.core.k8s:
      kubeconfig: "{{ settings.storage }}/k3s/k3s.yaml"
      state: present
      kind: Namespace
      api_version: v1
      name: "{{ ns }}"
