---
- hosts: localhost
  gather_facts: false
  become: true
  tasks:
  - name: Deploy from template
    template:
      src: "{{ settings.source }}/includes/playbooks/templates/letsencrypt.yml.j2"
      dest: "/tmp/le.yml"

  - name: Apply template
    kubernetes.core.k8s:
      kubeconfig: "{{ settings.storage }}/k3s/k3s.yaml"
      state: present
      src: "/tmp/le.yml"

  - name: delete temp file
    file:
      path: "/tmp/le.yml"
      state: absent

  - name: Apply redirect
    kubernetes.core.k8s:
      kubeconfig: "{{ settings.storage }}/k3s/k3s.yaml"
      state: present
      src: "{{ settings.source }}/includes/files/redirect.yml"


