---
- hosts: localhost
  gather_facts: false
  become: yes
  tasks:
  - name: Install letsencrypt
    kubernetes.core.k8s:
      kubeconfig: "{{ settings.storage }}/k3s/k3s.yaml"
      state: present
      namespace: cert-manager
      name: letsencrypt-production
      kind: ClusterIssuer
      definition:
        apiVersion: cert-manager.io/v1
        spec:
          acme:
            email: "{{ user.mail }}"
            server: https://acme-v02.api.letsencrypt.org/directory
            privateKeySecretRef:
              name: issuer-letsencrypt-production
            solvers:
              - dns01:
                  cloudflare:
                    apiTokenSecretRef:
                      key: "{{ cloudflare.api }}"
                      name: cloudflare-api-token-secret
                    email: "{{ user.mail }}"
  - name: Force letsencrypt
    kubernetes.core.k8s:
      kubeconfig: "{{ settings.storage }}/k3s/k3s.yaml"
      kind: Certificate
      namespace: cert-manager
      name: wildcard-cert
      definition:
        apiVersion: cert-manager.io/v1
        spec:
          secretName: wildcard-secret
          dnsNames:
            - "*.{{ user.domain }}"
          issuerRef:
            kind: ClusterIssuer
            name: letsencrypt-production