---
- hosts: localhost
  gather_facts: false
  become: true
  tasks:
  - name: Logrotate
    template:
      src: "{{ settings.source }}/includes/playbooks/templates/logrotate.j2"
      dest: /etc/logrotate.d/ansible
      force: true
