---
- hosts: localhost
  become: true
  gather_facts: false
  tasks:
    - name: create directory
      file:
        path: "{{ settings.storage }}/{{ directory }}"
        state: directory
      loop:
        - "local"
        - "Medias"
      loop_control:
        loop_var: directory

    - name: "MergerFS | Import 'mergerfs.service'"
      become: true
      template:
        src: "{{ settings.source }}/includes/playbooks/templates/mergerfs.service.j2"
        dest: /etc/systemd/system/mergerfs.service

    - name: "MergerFS | Start 'mergerfs.service'"
      become: true
      systemd: name=mergerfs.service state=started enabled=yes daemon_reload=yes
