---
- hosts: localhost
  become: yes
  gather_facts: false
  tasks:
    - name: "MergerFS | Import 'mergerfs.service'"
      become: yes
      template:
        src: "{{ settings.source }}/includes/playbooks/templates/mergerfs.service.j2"
        dest: /etc/systemd/system/mergerfs.service

    - name: "MergerFS | Start 'mergerfs.service'"
      become: yes
      systemd: name=mergerfs.service state=started enabled=yes daemon_reload=yes
