---
- hosts: localhost
  become: yes
  gather_facts: false
  tasks:
    - name: user_allow_other in fuse.conf
      become: yes
      lineinfile:
        path: /etc/fuse.conf
        line: user_allow_other

    - name: Import systemd rclone.service
      become: yes
      template:
        src: "{{ settings.source }}/includes/playbooks/templates/rclone.service.j2"
        dest: /etc/systemd/system/rclone.service
        owner: "root"
        group: "root"
        mode: 0775
        force: yes

    - name: Start rclone (Please Wait)
      become: yes
      systemd:
        daemon_reload: yes
        state: started
        name: rclone
        enabled: yes

    - name: Wait for service to be up
      pause:
        seconds: 10

    - name: Check if rclone is running
      shell: pgrep rclone
      ignore_errors: yes
      changed_when: false
      register: service_rclone_status

    - name: Report status of rclone
      fail:
        msg: |
          - "L'installation de rclone a échoué, Vérifier la configuration du fichier rclone.conf"
      when: service_rclone_status.rc != 0

    - debug:
        msg:
        - "L'installation de rclone s'est déroulée avec succés: Version Rclone {{ rclone_version.stdout }} installée"
        - "Le lancement de rclone s'est effectué avec succés"
      when: service_rclone_status.rc == 0