remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-multiple-languages-plugin
title: Kubeseed
description: Une seedbox sous Kubernetes

languages: ["fr", "en"]

site.baseurl: "/kubeseed"
